---
- name: Configuration de la machine Compta
  hosts: all
  become: yes

  tasks:
    - name: 1. Installer curl
      apt:
        name: curl
        state: present
        update_cache: yes

    - name: 2. Ajouter la clé GPG Wazuh
      shell: curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | apt-key add -

    - name: 3. Ajouter le dépôt Wazuh
      shell: echo "deb https://packages.wazuh.com/4.x/apt/ stable main" | tee /etc/apt/sources.list.d/wazuh.list

    - name: 4. Mettre à jour les paquets
      apt:
        update_cache: yes

    - name: 5. Installer l'agent Wazuh (Securite)
      apt:
        name: wazuh-agent
        state: present

    - name: 6. Installer Prometheus Node Exporter (Supervision)
      apt:
        name: prometheus-node-exporter
        state: present

    - name: 7. Installer Prometheus
      apt:
        name: prometheus
        state: present

    - name: 8. Installer Grafana
      shell: |
        curl -fsSL https://packages.grafana.com/gpg.key | gpg --dearmor -o /etc/apt/trusted.gpg.d/grafana.gpg
        echo "deb https://packages.grafana.com/oss/deb stable main" | tee /etc/apt/sources.list.d/grafana.list
        apt-get update
        apt-get install -y grafana

    - name: 9. Démarrer Grafana
      systemd:
        name: grafana-server
        state: started
        enabled: yes

    - name: 10. Démarrer Prometheus
      systemd:
        name: prometheus
        state: started
        enabled: yes